-- AlterTable
ALTER TABLE "Table"
ADD COLUMN "capacity" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "isReserved" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Order"
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "closedAt" TIMESTAMP(3);
